name: WideVariant mapping(legacy)
url: https://github.com/liebermanlab/WideVariant/
description: >
  Map reads with Bowtie 2, and post-process alignments with Sambamba:

    +----------------+----------+-----------------------------------------+
    | Step           | Tool     | Reason                                  |
    +================+==========+=========================================+
    |                | CutAdapt |                                         |
    +----------------+----------+-----------------------------------------+
    |                | Sickle   |                                         |
    +----------------+----------+-----------------------------------------+
    | Mapping        | Bowtie 2 | Perform read mapping                    |
    +----------------+----------+-----------------------------------------+
    | Grouping       | Picard   | Add or replace read groups              |
    +----------------+----------+-----------------------------------------+
    | Duplicates     | Picard   | Mark duplicates                         |
    +----------------+----------+-----------------------------------------+
    | Indexing       | Samtools | Index fasta genome sequence             |
    +----------------+----------------------------------------------------+
    | Pileups        | BCFTools |                                         |
    +----------------+----------+-----------------------------------------+
    | Call           | BCFTools |                                         |
    +----------------+----------+-----------------------------------------+
    | View           | BCFTools |                                         |
    +----------------+----------+-----------------------------------------+
    | Index          | Tabix    |                                         |
    +----------------+----------+-----------------------------------------+
authors:
  - Thomas Silvers
  - ...
